version: '3'
services:
  nginx:
      image: nginx:1.21.4-alpine
      restart: always
      depends_on:
        - echo-server
      ports:
          - "9013:80"
      volumes:
          - "./conf/default.conf:/etc/nginx/conf.d/default.conf"
          - "./logs:/var/log/nginx"

  echo-server:
    image: echo-server
    restart: always
    ports:
      - "9014:8001"