readTemplate('/home/ubuntu/weblogic/wls12214/wlserver/common/templates/wls/wls.jar')
cd('Servers/AdminServer')
set('ListenAddress','')
set('ListenPort', 7001)
cd('/Security/base_domain/User/weblogic')
cmo.setPassword('moxiaoxi.666')
setOption('OverwriteDomain', 'true')
writeDomain('/home/ubuntu/base_domain')
closeTemplate()
exit()