version: '3'
services:
  nginx:
      image: nginx:1.21.0-alpine
      restart: always
      depends_on:
        - nginx-echo-server
      ports:
          - "9013:80"
      volumes:
          - "./conf/default.conf:/etc/nginx/conf.d/default.conf"
          - "./logs:/var/log/nginx"

  nginx-echo-server:
    build: "../echo"
    restart: always
    ports:
      - "9014:8001"